import type { AdminLocale } from "@/lib/i18n/admin-locale";

const en = {
  eyebrow: "Business intelligence · FR-182",
  title: "Operations overview",
  description:
    "Revenue, operations, customers and growth across the selected Sonai scope.",
  filters: "Dashboard filters",
  openFilters: "Open filters",
  location: "Location",
  channel: "Channel",
  range: "Date range",
  comparison: "Compare with previous period",
  granularity: "Chart granularity",
  apply: "Apply filters",
  reset: "Reset",
  all: "All",
  today: "Today",
  days7: "Last 7 days",
  days30: "Last 30 days",
  month: "This month",
  quarter: "This quarter",
  year: "This year",
  custom: "Custom range",
  from: "From",
  to: "To",
  auto: "Automatic",
  day: "Daily",
  week: "Weekly",
  monthly: "Monthly",
  quarterly: "Quarterly",
  metrics: "Business metrics",
  revenue: "Revenue",
  orders: "Orders",
  grossProfit: "Gross profit",
  inventoryValue: "Inventory value",
  aov: "Average order value",
  deliverySuccess: "Delivery success",
  unavailable: "Unavailable",
  updated: "Updated",
  source: "Source",
  intelligence: "Primary intelligence",
  performance: "Revenue, profit and orders",
  download: "Download report",
  fullScreen: "Full screen",
  close: "Close",
  targets: "Performance targets",
  attention: "Attention queue",
  fulfilment: "Fulfilment flow",
  channels: "Channel contribution",
  geography: "Bangladesh order density",
  geographyHelp:
    "Aggregated district performance; no customer address or exact order pin is shown.",
  otherDistricts: "Other districts",
  unmapped: "Unmapped orders",
  district: "District",
  share: "Revenue share",
  inventory: "Inventory health",
  merchandising: "Merchandising intelligence",
  customers: "Customer growth",
  customer: "Customer",
  campaigns: "Campaign intelligence",
  activity: "Recent activity",
  recentOrders: "Recent orders",
  searchOrders: "Search order or customer",
  status: "Status",
  sort: "Sort",
  pageSize: "Rows",
  view: "Preview",
  export: "Export",
  previous: "Previous",
  next: "Next",
  saveView: "Save view",
  loadView: "Load view",
  units: "Units",
  total: "Total",
  margin: "Margin",
  stock: "Stock",
  returns: "Returns",
  growth: "Growth",
  product: "Product",
  category: "Category",
  collection: "Collection",
  branch: "Branch",
  noData: "No data in this scope",
  retry: "Try again",
  activeFilters: "active filters",
};

const bn: typeof en = {
  eyebrow: "ব্যবসায়িক তথ্য · FR-182",
  title: "অপারেশনস ওভারভিউ",
  description:
    "নির্বাচিত সোনাই পরিসরে আয়, অপারেশন, ক্রেতা ও প্রবৃদ্ধির চিত্র।",
  filters: "ড্যাশবোর্ড ফিল্টার",
  openFilters: "ফিল্টার খুলুন",
  location: "লোকেশন",
  channel: "চ্যানেল",
  range: "তারিখের পরিসর",
  comparison: "আগের সমান সময়ের সঙ্গে তুলনা",
  granularity: "চার্টের সময় বিভাজন",
  apply: "ফিল্টার প্রয়োগ",
  reset: "রিসেট",
  all: "সব",
  today: "আজ",
  days7: "গত ৭ দিন",
  days30: "গত ৩০ দিন",
  month: "এই মাস",
  quarter: "এই ত্রৈমাসিক",
  year: "এই বছর",
  custom: "নিজস্ব তারিখ",
  from: "শুরু",
  to: "শেষ",
  auto: "স্বয়ংক্রিয়",
  day: "দৈনিক",
  week: "সাপ্তাহিক",
  monthly: "মাসিক",
  quarterly: "ত্রৈমাসিক",
  metrics: "ব্যবসায়িক সূচক",
  revenue: "আয়",
  orders: "অর্ডার",
  grossProfit: "মোট মুনাফা",
  inventoryValue: "ইনভেন্টরির মূল্য",
  aov: "গড় অর্ডার মূল্য",
  deliverySuccess: "ডেলিভারি সাফল্য",
  unavailable: "উপাত্ত নেই",
  updated: "হালনাগাদ",
  source: "উৎস",
  intelligence: "মূল ব্যবসায়িক বিশ্লেষণ",
  performance: "আয়, মুনাফা ও অর্ডার",
  download: "রিপোর্ট ডাউনলোড",
  fullScreen: "পূর্ণ পর্দা",
  close: "বন্ধ",
  targets: "কর্মদক্ষতার লক্ষ্য",
  attention: "মনোযোগের তালিকা",
  fulfilment: "অর্ডার পূরণের ধাপ",
  channels: "চ্যানেলের অবদান",
  geography: "বাংলাদেশে অর্ডারের ঘনত্ব",
  geographyHelp:
    "জেলা-ভিত্তিক সমষ্টিগত ফলাফল; কোনো ক্রেতার ঠিকানা বা নির্দিষ্ট অর্ডার পিন দেখানো হয় না।",
  otherDistricts: "অন্যান্য জেলা",
  unmapped: "জেলা অনির্ধারিত",
  district: "জেলা",
  share: "আয়ের অংশ",
  inventory: "ইনভেন্টরি স্বাস্থ্য",
  merchandising: "পণ্য বিশ্লেষণ",
  customers: "ক্রেতা প্রবৃদ্ধি",
  customer: "ক্রেতা",
  campaigns: "ক্যাম্পেইন বিশ্লেষণ",
  activity: "সাম্প্রতিক কার্যক্রম",
  recentOrders: "সাম্প্রতিক অর্ডার",
  searchOrders: "অর্ডার বা ক্রেতা খুঁজুন",
  status: "অবস্থা",
  sort: "সাজান",
  pageSize: "সারি",
  view: "প্রিভিউ",
  export: "এক্সপোর্ট",
  previous: "আগের",
  next: "পরের",
  saveView: "ভিউ সংরক্ষণ",
  loadView: "ভিউ খুলুন",
  units: "ইউনিট",
  total: "মোট",
  margin: "মার্জিন",
  stock: "স্টক",
  returns: "রিটার্ন",
  growth: "প্রবৃদ্ধি",
  product: "পণ্য",
  category: "ক্যাটাগরি",
  collection: "কালেকশন",
  branch: "শাখা",
  noData: "এই পরিসরে কোনো তথ্য নেই",
  retry: "আবার চেষ্টা করুন",
  activeFilters: "টি সক্রিয় ফিল্টার",
};

export function dashboardCopy(locale: AdminLocale) {
  return locale === "bn" ? bn : en;
}
