import Link from "next/link";
import { PageHeader } from "@/components/ui/page-header";
import { MockDesignNotice } from "@/features/optimization/components/mock-design-notice";
import { ReportSchedules } from "@/features/optimization/components/report-schedules";
import { getFinanceWorkspace } from "@/features/optimization/server/queries";

export default async function ReportSchedulesPage() {
  const workspace = await getFinanceWorkspace();
  return (
    <div className="stack">
      <PageHeader
        eyebrow="Phase 8 · Delivery automation"
        title="Scheduled reports"
        description="Permission-aware XLSX/PDF delivery designs with explicit scope, recipient and artifact status."
        action={
          <Link className="button secondary" href="/reports">
            Run report now
          </Link>
        }
      />
      <MockDesignNotice>
        No XLSX/PDF artifact or email is generated by these schedules.
      </MockDesignNotice>
      <ReportSchedules schedules={workspace.reportSchedules} />
    </div>
  );
}
