export type TestStatus = "Not Run" | "Passed" | "Failed" | "Blocked";
export interface TestCase {
  id: string;
  requirement: string;
  module: string;
  route: string;
  role: string;
  priority: "High" | "Medium" | "Low";
  level: string;
  scenario: string;
  preconditions: string;
  data: string;
  steps: string;
  expected: string;
  mockScenario: string;
  automationCandidate: "Yes" | "No";
  automationFile: string;
  status: TestStatus;
  actual: string;
  evidence: string;
  defect: string;
  comments: string;
}

/** Canonical structured input for the verified Excel workbook and future test-management import. */
export const testCases: TestCase[] = [
  {
    id: "TC-AUTH-001",
    requirement: "FR-211",
    module: "Authentication",
    route: "/login",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "Sign in through mock boundary",
    preconditions: "Mock mode enabled",
    data: "owner@shonai.test",
    steps: "Open login; submit valid mock credentials",
    expected: "Dashboard opens and owner navigation is visible",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-two.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Live provider remains API-TODO",
  },
  {
    id: "TC-RBAC-001",
    requirement: "FR-214",
    module: "Permissions",
    route: "/payroll",
    role: "Cashier",
    priority: "High",
    level: "Integration",
    scenario: "Block restricted payroll access",
    preconditions: "MOCK_ROLE=cashier",
    data: "Payroll route",
    steps: "Request payroll page",
    expected: "Server permission boundary rejects access",
    mockScenario: "permission failure",
    automationCandidate: "Yes",
    automationFile: "src/lib/auth/permissions.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Navigation must also hide the route",
  },
  {
    id: "TC-DASH-001",
    requirement: "FR-182",
    module: "Dashboard",
    route: "/dashboard",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "View consolidated KPIs",
    preconditions: "Authenticated mock owner",
    data: "All locations; current month",
    steps: "Open dashboard",
    expected:
      "Revenue, orders, profit and inventory value render with BDT formatting",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "e2e/smoke.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-CAT-001",
    requirement: "FR-204",
    module: "Products",
    route: "/products",
    role: "Manager",
    priority: "High",
    level: "Component",
    scenario: "Browse products and variants",
    preconditions: "Catalog permission",
    data: "SH-SAR-1048",
    steps: "Open products; search by SKU",
    expected: "Matching product, price, variants and status are visible",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/features/catalog/tests/product-table.test.tsx",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-DASH-002",
    requirement: "FR-182",
    module: "Dashboard",
    route: "/dashboard",
    role: "Manager",
    priority: "High",
    level: "E2E",
    scenario: "Filter dashboard by location, channel and date range",
    preconditions: "Authenticated manager; deterministic summary data",
    data: "Online; all channels; seven days",
    steps: "Choose filters; update dashboard; reload the resulting URL",
    expected:
      "URL preserves filters and every summary section reflects the selected scope",
    mockScenario: "filtered success",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-two.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Trend chart includes an accessible textual summary",
  },
  {
    id: "TC-CAT-002",
    requirement: "FR-204",
    module: "Products",
    route: "/products/new",
    role: "Manager",
    priority: "High",
    level: "E2E",
    scenario: "Create, edit and archive a product",
    preconditions: "Catalog manage permission; active category",
    data: "Azure Test Saree; TEST-AZURE-001",
    steps: "Create product; open detail; edit name; save; confirm archive",
    expected:
      "Changes persist, version increases, and archived deep link remains available",
    mockScenario: "persistent mutation success",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-two.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Also covers FR-205 and FR-206",
  },
  {
    id: "TC-CAT-003",
    requirement: "FR-205",
    module: "Products",
    route: "/products/[productId]/edit",
    role: "Owner",
    priority: "High",
    level: "Integration",
    scenario: "Reject an edit submitted with a stale version",
    preconditions:
      "The same product has already been updated by another request",
    data: "Original version number",
    steps: "Update product once; submit a second update using the old version",
    expected:
      "Conflict message requests refresh and no data is silently overwritten",
    mockScenario: "optimistic conflict",
    automationCandidate: "Yes",
    automationFile: "src/features/catalog/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-CAT-004",
    requirement: "FR-208",
    module: "Variants",
    route: "/products/new",
    role: "Manager",
    priority: "High",
    level: "Unit",
    scenario: "Validate variant SKU and barcode uniqueness",
    preconditions: "Catalog fixtures initialized",
    data: "Duplicate SKU or barcode; independent color/size/price override",
    steps: "Submit duplicate identifiers, then submit valid distinct variants",
    expected:
      "Duplicates are rejected and valid variant fields persist independently",
    mockScenario: "validation failure and success",
    automationCandidate: "Yes",
    automationFile:
      "src/features/catalog/tests/catalog-schema.test.ts; src/features/catalog/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Also traces FR-152",
  },
  {
    id: "TC-CAT-005",
    requirement: "FR-204",
    module: "Product images",
    route: "/products/new",
    role: "Manager",
    priority: "Medium",
    level: "Component",
    scenario: "Validate selected image metadata",
    preconditions: "Product form is open",
    data: "JPEG/WebP under 5 MB, unsupported type, oversized file, short alt text",
    steps: "Select files; review previews; edit alt text; submit",
    expected:
      "Only allowed files preview and server validation rejects invalid metadata",
    mockScenario: "mixed file validation",
    automationCandidate: "Yes",
    automationFile: "src/features/catalog/tests/catalog-schema.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Binary upload is intentionally deferred",
  },
  {
    id: "TC-CAT-006",
    requirement: "FR-207",
    module: "CSV import",
    route: "/products/import",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "Preview and import valid rows from a mixed CSV",
    preconditions: "Required CSV headers; catalog manage permission",
    data: "One valid row plus malformed and duplicate-SKU rows",
    steps: "Choose CSV; inspect field errors; select importable rows; import",
    expected:
      "Preview explains invalid rows and summary counts only persisted valid products",
    mockScenario: "mixed valid and invalid rows",
    automationCandidate: "Yes",
    automationFile:
      "e2e/phase-two.spec.ts; src/features/catalog/tests/csv.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-CAT-007",
    requirement: "FR-209",
    module: "Categories",
    route: "/categories",
    role: "Manager",
    priority: "High",
    level: "Integration",
    scenario: "Protect hierarchy and active product references",
    preconditions: "Category has an active product",
    data: "Referenced category; parent cycle attempt",
    steps: "Try to archive referenced category; try to create a parent cycle",
    expected:
      "Both operations fail with actionable messages and existing hierarchy remains intact",
    mockScenario: "business-rule conflict",
    automationCandidate: "Yes",
    automationFile: "src/features/catalog/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-CAT-008",
    requirement: "FR-153",
    module: "Barcodes",
    route: "/products/barcodes",
    role: "Manager",
    priority: "High",
    level: "E2E",
    scenario: "Render and print Code 128 labels",
    preconditions: "Active products with unique variant barcodes",
    data: "Product, variant, SKU, price and barcode",
    steps: "Open barcode page; verify generated image; open print preview",
    expected:
      "Every active SKU has a scannable Code 128 label and print-only layout",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-two.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Also traces FR-154; EAN-13 remains deferred",
  },
  {
    id: "TC-RBAC-002",
    requirement: "FR-214",
    module: "Catalog permissions",
    route: "/products",
    role: "Cashier / Support",
    priority: "High",
    level: "Integration",
    scenario: "Allow catalog viewing but deny mutation",
    preconditions: "Mock role is Cashier or Support",
    data: "Product list and create action",
    steps: "Open product list; inspect actions; invoke create action directly",
    expected:
      "Read data is visible, manage controls are hidden, and server action returns no mutation",
    mockScenario: "permission failure",
    automationCandidate: "Yes",
    automationFile: "src/lib/auth/permissions.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Server authorization is required even when controls are hidden",
  },
  {
    id: "TC-INV-001",
    requirement: "FR-142",
    module: "Inventory",
    route: "/inventory",
    role: "Manager",
    priority: "High",
    level: "E2E",
    scenario: "Compare location stock",
    preconditions: "Inventory permission",
    data: "SH-SHL-0097",
    steps: "Open inventory; inspect branch and online columns",
    expected:
      "Location values reconcile to consolidated total and critical status",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-MOV-001",
    requirement: "FR-150",
    module: "Stock movements",
    route: "/stock-movements",
    role: "Manager",
    priority: "High",
    level: "Integration",
    scenario: "Review traceable movement",
    preconditions: "Inventory permission",
    data: "MOV-24071",
    steps: "Open movement listing",
    expected: "Type, SKU, quantity, location, actor and outcome are visible",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-ORD-001",
    requirement: "FR-172",
    module: "Orders",
    route: "/orders",
    role: "Cashier",
    priority: "High",
    level: "E2E",
    scenario: "Review fulfillment state",
    preconditions: "Order permission",
    data: "SH-260729-1842",
    steps: "Open orders; inspect record",
    expected: "Customer, channel, location, total, payment and status render",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-CMP-001",
    requirement: "FR-178",
    module: "Complaints",
    route: "/complaints",
    role: "Support",
    priority: "High",
    level: "E2E",
    scenario: "Track complaint ownership",
    preconditions: "Support role",
    data: "CMP-00638",
    steps: "Open complaints",
    expected: "Topic, channel, assignee, update time and progress are visible",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-PO-001",
    requirement: "FR-163",
    module: "Purchase orders",
    route: "/purchase-orders",
    role: "Manager",
    priority: "High",
    level: "E2E",
    scenario: "Track purchase order status",
    preconditions: "Procurement permission",
    data: "PO-2026-0086",
    steps: "Open purchase orders",
    expected: "Supplier, lines, cost, expected date, approver and state render",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-REP-001",
    requirement: "FR-189",
    module: "Reports",
    route: "/reports",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "Review export history",
    preconditions: "Report permission",
    data: "RPT-260729-24",
    steps: "Open reports",
    expected: "Report range, scope, format and readiness are visible",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Export mutation awaits backend",
  },
  {
    id: "TC-A11Y-001",
    requirement: "NFR-340",
    module: "Application shell",
    route: "/dashboard",
    role: "Owner",
    priority: "High",
    level: "Accessibility",
    scenario: "Keyboard navigation and skip link",
    preconditions: "Authenticated user",
    data: "Keyboard only",
    steps: "Focus first control; activate skip link; traverse navigation",
    expected: "Focus is visible and order is logical",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-RESP-001",
    requirement: "NFR-335",
    module: "Application shell",
    route: "/inventory",
    role: "Manager",
    priority: "High",
    level: "Responsive",
    scenario: "Use dense table at 360px",
    preconditions: "360px viewport",
    data: "Inventory listing",
    steps: "Open inventory; navigate and scroll table",
    expected: "No page-level horizontal overflow; actions remain reachable",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-DATA-001",
    requirement: "NFR-352",
    module: "Data boundary",
    route: "Server",
    role: "System",
    priority: "High",
    level: "Unit",
    scenario: "Reject malformed repository row",
    preconditions: "Schema available",
    data: "Record without id",
    steps: "Parse invalid collection",
    expected: "Runtime validation fails",
    mockScenario: "malformed response",
    automationCandidate: "Yes",
    automationFile: "src/features/modules/tests/module-schema.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-SEC-001",
    requirement: "NFR-356",
    module: "Settings",
    route: "/settings",
    role: "Owner",
    priority: "High",
    level: "Security",
    scenario: "Keep credentials server-side",
    preconditions: "Mock integrations",
    data: "Courier/payment settings",
    steps: "Inspect rendered page and client bundle",
    expected: "No secret or realistic credential appears",
    mockScenario: "success",
    automationCandidate: "No",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Manual bundle inspection",
  },
];
