export type TestStatus = "Not Run" | "Passed" | "Failed" | "Blocked";
export interface TestCase {
  id: string;
  requirement: string;
  module: string;
  route: string;
  role: string;
  priority: "High" | "Medium" | "Low";
  level: string;
  scenario: string;
  preconditions: string;
  data: string;
  steps: string;
  expected: string;
  mockScenario: string;
  automationCandidate: "Yes" | "No";
  automationFile: string;
  status: TestStatus;
  actual: string;
  evidence: string;
  defect: string;
  comments: string;
}

/** Canonical structured input for the verified Excel workbook and future test-management import. */
export const testCases: TestCase[] = [
  {
    id: "TC-AUTH-001",
    requirement: "FR-211",
    module: "Authentication",
    route: "/login",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "Sign in through mock boundary",
    preconditions: "Mock mode enabled",
    data: "owner@shonai.test",
    steps: "Open login; submit valid mock credentials",
    expected: "Dashboard opens and owner navigation is visible",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-two.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Live provider remains API-TODO",
  },
  {
    id: "TC-RBAC-001",
    requirement: "FR-214",
    module: "Permissions",
    route: "/payroll",
    role: "Cashier",
    priority: "High",
    level: "Integration",
    scenario: "Block restricted payroll access",
    preconditions: "MOCK_ROLE=cashier",
    data: "Payroll route",
    steps: "Request payroll page",
    expected: "Server permission boundary rejects access",
    mockScenario: "permission failure",
    automationCandidate: "Yes",
    automationFile: "src/lib/auth/permissions.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Navigation must also hide the route",
  },
  {
    id: "TC-DASH-001",
    requirement: "FR-182",
    module: "Dashboard",
    route: "/dashboard",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "View consolidated KPIs",
    preconditions: "Authenticated mock owner",
    data: "All locations; current month",
    steps: "Open dashboard",
    expected:
      "Revenue, orders, profit and inventory value render with BDT formatting",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "e2e/smoke.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-CAT-001",
    requirement: "FR-204",
    module: "Products",
    route: "/products",
    role: "Manager",
    priority: "High",
    level: "Component",
    scenario: "Browse products and variants",
    preconditions: "Catalog permission",
    data: "SH-SAR-1048",
    steps: "Open products; search by SKU",
    expected: "Matching product, price, variants and status are visible",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/features/catalog/tests/product-table.test.tsx",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-DASH-002",
    requirement: "FR-182",
    module: "Dashboard",
    route: "/dashboard",
    role: "Manager",
    priority: "High",
    level: "E2E",
    scenario: "Filter dashboard by location, channel and date range",
    preconditions: "Authenticated manager; deterministic summary data",
    data: "Online; all channels; seven days",
    steps: "Choose filters; update dashboard; reload the resulting URL",
    expected:
      "URL preserves filters and every summary section reflects the selected scope",
    mockScenario: "filtered success",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-two.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Trend chart includes an accessible textual summary",
  },
  {
    id: "TC-CAT-002",
    requirement: "FR-204",
    module: "Products",
    route: "/products/new",
    role: "Manager",
    priority: "High",
    level: "E2E",
    scenario: "Create, edit and archive a product",
    preconditions: "Catalog manage permission; active category",
    data: "Azure Test Saree; TEST-AZURE-001",
    steps: "Create product; open detail; edit name; save; confirm archive",
    expected:
      "Changes persist, version increases, and archived deep link remains available",
    mockScenario: "persistent mutation success",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-two.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Also covers FR-205 and FR-206",
  },
  {
    id: "TC-CAT-003",
    requirement: "FR-205",
    module: "Products",
    route: "/products/[productId]/edit",
    role: "Owner",
    priority: "High",
    level: "Integration",
    scenario: "Reject an edit submitted with a stale version",
    preconditions:
      "The same product has already been updated by another request",
    data: "Original version number",
    steps: "Update product once; submit a second update using the old version",
    expected:
      "Conflict message requests refresh and no data is silently overwritten",
    mockScenario: "optimistic conflict",
    automationCandidate: "Yes",
    automationFile: "src/features/catalog/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-CAT-004",
    requirement: "FR-208",
    module: "Variants",
    route: "/products/new",
    role: "Manager",
    priority: "High",
    level: "Unit",
    scenario: "Validate variant SKU and barcode uniqueness",
    preconditions: "Catalog fixtures initialized",
    data: "Duplicate SKU or barcode; independent color/size/price override",
    steps: "Submit duplicate identifiers, then submit valid distinct variants",
    expected:
      "Duplicates are rejected and valid variant fields persist independently",
    mockScenario: "validation failure and success",
    automationCandidate: "Yes",
    automationFile:
      "src/features/catalog/tests/catalog-schema.test.ts; src/features/catalog/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Also traces FR-152",
  },
  {
    id: "TC-CAT-005",
    requirement: "FR-204",
    module: "Product images",
    route: "/products/new",
    role: "Manager",
    priority: "Medium",
    level: "Component",
    scenario: "Validate selected image metadata",
    preconditions: "Product form is open",
    data: "JPEG/WebP under 5 MB, unsupported type, oversized file, short alt text",
    steps: "Select files; review previews; edit alt text; submit",
    expected:
      "Only allowed files preview and server validation rejects invalid metadata",
    mockScenario: "mixed file validation",
    automationCandidate: "Yes",
    automationFile: "src/features/catalog/tests/catalog-schema.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Binary upload is intentionally deferred",
  },
  {
    id: "TC-CAT-006",
    requirement: "FR-207",
    module: "CSV import",
    route: "/products/import",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "Preview and import valid rows from a mixed CSV",
    preconditions: "Required CSV headers; catalog manage permission",
    data: "One valid row plus malformed and duplicate-SKU rows",
    steps: "Choose CSV; inspect field errors; select importable rows; import",
    expected:
      "Preview explains invalid rows and summary counts only persisted valid products",
    mockScenario: "mixed valid and invalid rows",
    automationCandidate: "Yes",
    automationFile:
      "e2e/phase-two.spec.ts; src/features/catalog/tests/csv.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-CAT-007",
    requirement: "FR-209",
    module: "Categories",
    route: "/categories",
    role: "Manager",
    priority: "High",
    level: "Integration",
    scenario: "Protect hierarchy and active product references",
    preconditions: "Category has an active product",
    data: "Referenced category; parent cycle attempt",
    steps: "Try to archive referenced category; try to create a parent cycle",
    expected:
      "Both operations fail with actionable messages and existing hierarchy remains intact",
    mockScenario: "business-rule conflict",
    automationCandidate: "Yes",
    automationFile: "src/features/catalog/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-CAT-008",
    requirement: "FR-153",
    module: "Barcodes",
    route: "/products/barcodes",
    role: "Manager",
    priority: "High",
    level: "E2E",
    scenario: "Render and print Code 128 labels",
    preconditions: "Active products with unique variant barcodes",
    data: "Product, variant, SKU, price and barcode",
    steps: "Open barcode page; verify generated image; open print preview",
    expected:
      "Every active SKU has a scannable Code 128 label and print-only layout",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-two.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Also traces FR-154; EAN-13 remains deferred",
  },
  {
    id: "TC-RBAC-002",
    requirement: "FR-214",
    module: "Catalog permissions",
    route: "/products",
    role: "Cashier / Support",
    priority: "High",
    level: "Integration",
    scenario: "Allow catalog viewing but deny mutation",
    preconditions: "Mock role is Cashier or Support",
    data: "Product list and create action",
    steps: "Open product list; inspect actions; invoke create action directly",
    expected:
      "Read data is visible, manage controls are hidden, and server action returns no mutation",
    mockScenario: "permission failure",
    automationCandidate: "Yes",
    automationFile: "src/lib/auth/permissions.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Server authorization is required even when controls are hidden",
  },
  {
    id: "TC-INV-001",
    requirement: "FR-142",
    module: "Inventory",
    route: "/inventory",
    role: "Manager",
    priority: "High",
    level: "E2E",
    scenario: "Compare location stock",
    preconditions: "Inventory permission",
    data: "SH-SHL-0097",
    steps: "Open inventory; inspect branch and online columns",
    expected:
      "Location values reconcile to consolidated total and critical status",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-MOV-001",
    requirement: "FR-150",
    module: "Stock movements",
    route: "/stock-movements",
    role: "Manager",
    priority: "High",
    level: "Integration",
    scenario: "Review traceable movement",
    preconditions: "Inventory permission",
    data: "MOV-24071",
    steps: "Open movement listing",
    expected: "Type, SKU, quantity, location, actor and outcome are visible",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-ORD-001",
    requirement: "FR-172",
    module: "Orders",
    route: "/orders",
    role: "Cashier",
    priority: "High",
    level: "E2E",
    scenario: "Review fulfillment state",
    preconditions: "Order permission",
    data: "SH-260729-1842",
    steps: "Open orders; inspect record",
    expected: "Customer, channel, location, total, payment and status render",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-CMP-001",
    requirement: "FR-178",
    module: "Complaints",
    route: "/complaints",
    role: "Support",
    priority: "High",
    level: "E2E",
    scenario: "Track complaint ownership",
    preconditions: "Support role",
    data: "CMP-00638",
    steps: "Open complaints",
    expected: "Topic, channel, assignee, update time and progress are visible",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-PO-001",
    requirement: "FR-163",
    module: "Purchase orders",
    route: "/purchase-orders",
    role: "Manager",
    priority: "High",
    level: "E2E",
    scenario: "Track purchase order status",
    preconditions: "Procurement permission",
    data: "PO-2026-0086",
    steps: "Open purchase orders",
    expected: "Supplier, lines, cost, expected date, approver and state render",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-REP-001",
    requirement: "FR-189",
    module: "Reports",
    route: "/reports",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "Review export history",
    preconditions: "Report permission",
    data: "RPT-260729-24",
    steps: "Open reports",
    expected: "Report range, scope, format and readiness are visible",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Export mutation awaits backend",
  },
  {
    id: "TC-A11Y-001",
    requirement: "NFR-340",
    module: "Application shell",
    route: "/dashboard",
    role: "Owner",
    priority: "High",
    level: "Accessibility",
    scenario: "Keyboard navigation and skip link",
    preconditions: "Authenticated user",
    data: "Keyboard only",
    steps: "Focus first control; activate skip link; traverse navigation",
    expected: "Focus is visible and order is logical",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-RESP-001",
    requirement: "NFR-335",
    module: "Application shell",
    route: "/inventory",
    role: "Manager",
    priority: "High",
    level: "Responsive",
    scenario: "Use dense table at 360px",
    preconditions: "360px viewport",
    data: "Inventory listing",
    steps: "Open inventory; navigate and scroll table",
    expected: "No page-level horizontal overflow; actions remain reachable",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-DATA-001",
    requirement: "NFR-352",
    module: "Data boundary",
    route: "Server",
    role: "System",
    priority: "High",
    level: "Unit",
    scenario: "Reject malformed repository row",
    preconditions: "Schema available",
    data: "Record without id",
    steps: "Parse invalid collection",
    expected: "Runtime validation fails",
    mockScenario: "malformed response",
    automationCandidate: "Yes",
    automationFile: "src/features/modules/tests/module-schema.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-SEC-001",
    requirement: "NFR-356",
    module: "Settings",
    route: "/settings",
    role: "Owner",
    priority: "High",
    level: "Security",
    scenario: "Keep credentials server-side",
    preconditions: "Mock integrations",
    data: "Courier/payment settings",
    steps: "Inspect rendered page and client bundle",
    expected: "No secret or realistic credential appears",
    mockScenario: "success",
    automationCandidate: "No",
    automationFile: "",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Manual bundle inspection",
  },
  {
    id: "TC-INV-001",
    requirement: "FR-140",
    module: "Inventory",
    route: "/inventory",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Migrate catalog stock into unified inventory",
    preconditions: "Legacy catalog.json exists",
    data: "Deterministic Phase 2 fixtures",
    steps: "Open unified store; inspect balances and movements",
    expected:
      "Legacy units appear as Online opening balances with audit movements; source file remains",
    mockScenario: "legacy migration",
    automationCandidate: "Yes",
    automationFile: "src/lib/mock-store/mock-store.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-INV-002",
    requirement: "FR-146",
    module: "Inventory",
    route: "/stock-movements/new",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Record stock adjustment with optimistic version",
    preconditions: "Valid SKU balance",
    data: "+2 receipt",
    steps: "Submit receipt; retry stale different command",
    expected: "Receipt persists once and stale version is rejected",
    mockScenario: "success and conflict",
    automationCandidate: "Yes",
    automationFile: "src/features/inventory/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-INV-003",
    requirement: "FR-150",
    module: "Transfers",
    route: "/inventory/transfers",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Dispatch and receive a transfer",
    preconditions: "Source has available stock",
    data: "Online to Rupnagar, 1 unit",
    steps: "Create draft; dispatch; receive",
    expected:
      "Source deducts at dispatch and destination adds at receipt with paired movements",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/features/inventory/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-INV-004",
    requirement: "FR-151",
    module: "Stock counts",
    route: "/stock-counts/[countId]",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Approve physical-count variance",
    preconditions: "Count started and submitted",
    data: "+1 variance",
    steps: "Record count; submit; approve",
    expected:
      "Count is approved and one correction movement changes stock atomically",
    mockScenario: "variance",
    automationCandidate: "Yes",
    automationFile: "src/features/inventory/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-ORD-001",
    requirement: "FR-166",
    module: "Orders",
    route: "/orders/new",
    role: "Cashier",
    priority: "High",
    level: "Component",
    scenario: "Create multi-line manual order",
    preconditions: "Active variants available",
    data: "Bangladesh phone and two SKUs",
    steps: "Enter customer; add second line; submit",
    expected: "Server prices lines and creates SH-YYMMDD-#### order",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-three.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-ORD-002",
    requirement: "FR-170",
    module: "Fulfillment",
    route: "/orders/[orderId]",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Reserve and cancel order",
    preconditions: "Placed order assigned to stocked location",
    data: "One unit",
    steps: "Confirm; inspect reserved; cancel",
    expected:
      "Confirmation reserves one and cancellation releases one without changing on-hand",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/features/orders/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-ORD-003",
    requirement: "FR-172",
    module: "Fulfillment",
    route: "/orders/[orderId]",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Ship and deliver paid order",
    preconditions: "Confirmed paid order",
    data: "Mock courier",
    steps: "Pick; pack; ship; deliver",
    expected:
      "Shipment consumes reservation and on-hand, creates tracking reference, then records delivery",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/features/orders/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-ORD-004",
    requirement: "FR-175",
    module: "Returns",
    route: "/orders/[orderId]",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Receive delivered return",
    preconditions: "Delivered paid order",
    data: "One returned unit",
    steps: "Request; approve; receive",
    expected:
      "Stock is restored and mock refund status is recorded without over-return",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/features/orders/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-RBAC-003",
    requirement: "FR-214",
    module: "Phase 3 permissions",
    route: "/inventory; /orders",
    role: "Cashier",
    priority: "High",
    level: "Unit",
    scenario: "Enforce granular branch operations",
    preconditions: "Cashier assigned to Rupnagar",
    data: "Adjust, cancel and approve commands",
    steps: "Evaluate permission matrix and protected actions",
    expected:
      "Cashier can view/count/create/fulfill but cannot adjust, approve, cancel or refund",
    mockScenario: "permission failure",
    automationCandidate: "Yes",
    automationFile: "src/lib/auth/permissions.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "",
  },
  {
    id: "TC-DATA-003",
    requirement: "NFR-352",
    module: "Unified store",
    route: "Server",
    role: "System",
    priority: "High",
    level: "Repository",
    scenario: "Preserve malformed unified data",
    preconditions: "Invalid shonai.json",
    data: "Schema-incomplete JSON",
    steps: "Read store; inspect original file",
    expected: "STORE_INVALID is raised and invalid file is unchanged",
    mockScenario: "malformed store",
    automationCandidate: "Yes",
    automationFile: "src/lib/mock-store/mock-store.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Workbook export blocked until artifact runtime is available",
  },
  {
    id: "TC-CUS-001",
    requirement: "FR-127",
    module: "Customers",
    route: "/customers/new",
    role: "Cashier",
    priority: "High",
    level: "Repository",
    scenario: "Normalize and deduplicate customer identity",
    preconditions: "Customer permission enabled",
    data: "01700-000003 and duplicate +880 form",
    steps: "Create customer; retry equivalent phone",
    expected:
      "Phone is normalized and duplicate creation links to a safe conflict",
    mockScenario: "success and duplicate",
    automationCandidate: "Yes",
    automationFile: "src/features/customers/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Repository verification passed",
    evidence: "Vitest",
    defect: "",
    comments: "Historical order snapshots remain immutable",
  },
  {
    id: "TC-LOY-001",
    requirement: "FR-121; FR-125; FR-215",
    module: "Loyalty",
    route: "/customers/[customerId]",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Adjust loyalty without allowing negative balance",
    preconditions: "Customer enrolled",
    data: "+25 then -30",
    steps: "Credit points; attempt excessive debit",
    expected: "Credit is recorded once and excessive debit is rejected",
    mockScenario: "validation failure",
    automationCandidate: "Yes",
    automationFile: "src/features/customers/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Repository verification passed",
    evidence: "Vitest",
    defect: "",
    comments:
      "Delivery earning and received-return reversal are integrated with orders",
  },
  {
    id: "TC-CMP-001",
    requirement: "FR-177; FR-178; FR-181",
    module: "Complaints",
    route: "/complaints/[complaintId]",
    role: "Support",
    priority: "High",
    level: "Repository",
    scenario: "Progress and reopen an auditable complaint",
    preconditions: "Complaint linked to customer",
    data: "Delivery complaint",
    steps: "Assign; acknowledge; progress; resolve; close; reopen",
    expected:
      "Only valid transitions succeed and timeline retains every change",
    mockScenario: "success and invalid resolution",
    automationCandidate: "Yes",
    automationFile: "src/features/complaints/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Repository verification passed",
    evidence: "Vitest",
    defect: "",
    comments: "Customer updates are fictional events only",
  },
  {
    id: "TC-SUP-001",
    requirement: "FR-161",
    module: "Suppliers",
    route: "/suppliers/new",
    role: "Manager",
    priority: "Medium",
    level: "Component",
    scenario: "Create supplier with variant mappings",
    preconditions: "Active catalog variants",
    data: "Supplier contact, terms, SKU mapping",
    steps: "Complete supplier form; add variant mapping; save",
    expected: "Supplier and commercial mapping persist with a stable code",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-four.spec.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments: "Binary documents and supplier messaging are deferred",
  },
  {
    id: "TC-PO-001",
    requirement: "FR-161; FR-162",
    module: "Purchase Orders",
    route: "/purchase-orders/[purchaseOrderId]",
    role: "Owner",
    priority: "High",
    level: "Repository",
    scenario: "Approve every submitted purchase order",
    preconditions: "Draft PO exists",
    data: "One SKU and destination",
    steps: "Submit; approve; supplier confirm",
    expected:
      "Commercial lines freeze and authorized approval is retained in timeline",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/features/procurement/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Repository verification passed",
    evidence: "Vitest",
    defect: "",
    comments: "Managers may approve their own POs in Phase 4",
  },
  {
    id: "TC-PO-002",
    requirement: "FR-163; FR-164",
    module: "Receiving",
    route: "/purchase-orders/[purchaseOrderId]/receive",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Partially receive accepted, damaged, and rejected quantities",
    preconditions: "Supplier-confirmed PO",
    data: "6 accepted, 1 damaged from 10 ordered",
    steps: "Record receipt; inspect PO, balance, and movement",
    expected:
      "Only six accepted units enter stock and PO remains partially received",
    mockScenario: "partial receipt",
    automationCandidate: "Yes",
    automationFile: "src/features/procurement/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Repository verification passed",
    evidence: "Vitest",
    defect: "",
    comments: "Costs do not rewrite catalog valuation",
  },
  {
    id: "TC-PO-003",
    requirement: "FR-164",
    module: "Receiving",
    route: "/purchase-orders/[purchaseOrderId]/receive",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Block strict over-receipt",
    preconditions: "PO already partially received",
    data: "Receipt exceeds remaining quantity",
    steps: "Submit excess receipt",
    expected: "RECEIPT_MISMATCH is returned and inventory is unchanged",
    mockScenario: "receipt mismatch",
    automationCandidate: "Yes",
    automationFile: "src/features/procurement/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Repository verification passed",
    evidence: "Vitest",
    defect: "",
    comments: "PO amendments are deferred",
  },
  {
    id: "TC-RBAC-004",
    requirement: "FR-214",
    module: "Phase 4 Permissions",
    route: "/customers; /complaints; /purchase-orders",
    role: "Cashier/Support",
    priority: "High",
    level: "Unit",
    scenario: "Enforce relationship and procurement boundaries",
    preconditions: "Role matrix loaded",
    data: "Phase 4 permissions",
    steps: "Evaluate Owner, Manager, Cashier, and Support capabilities",
    expected:
      "Only Owner configures loyalty; cashier/support cannot mutate procurement",
    mockScenario: "permission failure",
    automationCandidate: "Yes",
    automationFile: "src/lib/auth/permissions.test.ts",
    status: "Passed",
    actual: "Permission verification passed",
    evidence: "Vitest",
    defect: "",
    comments: "Queries and actions authorize independently",
  },
  {
    id: "TC-DATA-004",
    requirement: "NFR-328; NFR-352",
    module: "Unified Store",
    route: "Server",
    role: "System",
    priority: "High",
    level: "Repository",
    scenario: "Migrate Phase 3 customer snapshots through schema version 4",
    preconditions: "Valid version 2 store",
    data: "Captured orders with fictional contacts",
    steps: "Read store; inspect customers and order relationships",
    expected:
      "Customers are created deterministically, orders link by customerId, and no points are backfilled",
    mockScenario: "migration",
    automationCandidate: "Yes",
    automationFile: "src/lib/mock-store/mock-store.test.ts",
    status: "Passed",
    actual: "Migration verification passed",
    evidence: "Vitest",
    defect: "",
    comments: "Original customer snapshots remain unchanged",
  },
  {
    id: "TC-CAM-001",
    requirement: "FR-131; FR-132; FR-219",
    module: "Campaigns",
    route: "/campaigns/[campaignId]",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Schedule one deterministic non-stacking discount",
    preconditions: "Active catalog SKU and overlapping campaigns",
    data: "10% and 20% full-store campaigns",
    steps: "Create; schedule; activate; calculate eligible order discount",
    expected:
      "The single largest eligible discount wins with stable tie-breaking",
    mockScenario: "overlapping campaigns",
    automationCandidate: "Yes",
    automationFile: "src/features/campaigns/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Repository and browser verification passed",
    evidence: "Vitest; Playwright",
    defect: "",
    comments: "Storefront publication remains an API boundary",
  },
  {
    id: "TC-REP-001",
    requirement: "FR-186; FR-187; FR-189",
    module: "Reports",
    route: "/reports; /api/reports/export",
    role: "Owner",
    priority: "High",
    level: "Integration",
    scenario: "Run source-backed reports and export safe CSV",
    preconditions: "Unified store contains operational data",
    data: "Sales, profit, inventory, campaign, procurement, payroll",
    steps: "Select report filters; run; export CSV",
    expected:
      "Metrics reconcile to rows and formula-like cells are neutralized",
    mockScenario: "success and empty filters",
    automationCandidate: "Yes",
    automationFile: "src/features/reports/tests/csv.test.ts",
    status: "Passed",
    actual: "CSV safety and report UI verified",
    evidence: "Vitest; Playwright",
    defect: "",
    comments:
      "Scheduled email and production Excel export are deferred adapters",
  },
  {
    id: "TC-STF-001",
    requirement: "FR-194; FR-196; FR-197; FR-198",
    module: "Staff",
    route: "/staff; /staff/new; /staff/[staffId]",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Create a unique branch-scoped staff profile",
    preconditions: "Active branch exists",
    data: "Fictional staff contact and employment record",
    steps: "Create profile; inspect list; attempt duplicate contact",
    expected: "Profile persists and duplicate phone or email is rejected",
    mockScenario: "success and duplicate",
    automationCandidate: "Yes",
    automationFile: "src/features/administration/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Repository verification passed",
    evidence: "Vitest",
    defect: "",
    comments: "No NID, tax, bank, or real employee secrets are stored",
  },
  {
    id: "TC-ATT-001",
    requirement: "FR-199; FR-200",
    module: "Attendance and Leave",
    route: "/attendance; /attendance/leave",
    role: "Cashier/Manager",
    priority: "High",
    level: "E2E",
    scenario: "Record scoped attendance and decide leave once",
    preconditions: "Staff account linked to profile",
    data: "Absent day and pending leave request",
    steps: "Record attendance; request leave; approve or reject",
    expected:
      "Branch/self scope is enforced and decided requests cannot transition again",
    mockScenario: "success and invalid transition",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-five.spec.ts",
    status: "Passed",
    actual: "Desktop/mobile browser verification passed",
    evidence: "Playwright",
    defect: "",
    comments: "Attendance hardware integration is deferred",
  },
  {
    id: "TC-PAY-001",
    requirement: "FR-201; FR-202; FR-203",
    module: "Payroll",
    route: "/payroll/[payrollId]",
    role: "Owner",
    priority: "High",
    level: "Repository",
    scenario: "Calculate, submit, approve, and pay a payroll snapshot",
    preconditions: "Effective salary and monthly attendance exist",
    data: "One absence and fixed salary inputs",
    steps: "Create payroll; verify deduction; submit; approve; retry; pay",
    expected:
      "Integer calculations are stable, approval is ordered, and retry is idempotent",
    mockScenario: "success and duplicate command",
    automationCandidate: "Yes",
    automationFile: "src/features/workforce/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Repository and browser verification passed",
    evidence: "Vitest; Playwright",
    defect: "",
    comments: "No bank/payment details are stored",
  },
  {
    id: "TC-USR-001",
    requirement: "FR-210; FR-212",
    module: "Users",
    route: "/users",
    role: "Owner",
    priority: "High",
    level: "Functional",
    scenario: "Create and administer a staff-linked mock account",
    preconditions: "Staff profile without account",
    data: "Fictional username and role",
    steps: "Create account; deactivate; record password reset",
    expected:
      "No credential or reset token is persisted and every change is audited",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/features/administration/tests/file-repository.test.ts",
    status: "Not Run",
    actual: "",
    evidence: "",
    defect: "",
    comments:
      "Real identity and reset delivery remain auth-provider boundaries",
  },
  {
    id: "TC-RBAC-005",
    requirement: "FR-195; FR-211; NFR-319",
    module: "Roles",
    route: "/roles",
    role: "Owner",
    priority: "High",
    level: "Unit",
    scenario: "Persist granular role permissions without weakening Owner",
    preconditions: "Schema-v4 role profiles initialized",
    data: "Cashier report view and reduced Owner list",
    steps:
      "Update Cashier; attempt to remove Owner permissions; authorize server query",
    expected: "Cashier update persists and Owner weakening is rejected",
    mockScenario: "success and validation failure",
    automationCandidate: "Yes",
    automationFile: "src/features/administration/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Permission repository verification passed",
    evidence: "Vitest",
    defect: "",
    comments:
      "Navigation remains advisory; server authorization reads persisted profiles",
  },
  {
    id: "TC-AUD-001",
    requirement: "NFR-351; NFR-358",
    module: "Audit",
    route: "/audit-log",
    role: "Manager",
    priority: "High",
    level: "Repository",
    scenario: "Retain immutable Phase 5 administrative events",
    preconditions: "Phase 5 mutation completed",
    data: "Staff, campaign, payroll, role, or settings mutation",
    steps: "Perform mutation; filter audit list",
    expected:
      "Actor, entity, action, timestamp, and safe summary remain append-only",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/features/administration/tests/file-repository.test.ts",
    status: "Passed",
    actual: "Audit append verification passed",
    evidence: "Vitest",
    defect: "",
    comments: "Production immutable retention is a backend boundary",
  },
  {
    id: "TC-DATA-005",
    requirement: "NFR-328; NFR-352",
    module: "Unified Store",
    route: "Server",
    role: "System",
    priority: "High",
    level: "Repository",
    scenario: "Migrate schema version 3 to version 4 atomically",
    preconditions: "Valid Phase 4 store",
    data: "Customers, complaints, procurement, orders, and inventory history",
    steps: "Read version 3 store; validate version 4; inspect migration audit",
    expected:
      "Earlier records remain intact and deterministic Phase 5 foundations are added",
    mockScenario: "migration",
    automationCandidate: "Yes",
    automationFile: "src/lib/mock-store/mock-store.test.ts",
    status: "Passed",
    actual: "Migration verification passed",
    evidence: "Vitest",
    defect: "",
    comments: "Malformed stores remain preserved",
  },
  {
    id: "TC-SEC-006",
    requirement: "NFR-343; NFR-344; NFR-345",
    module: "Security Headers",
    route: "All routes",
    role: "All",
    priority: "High",
    level: "Integration",
    scenario: "Apply browser security policy consistently",
    preconditions: "Application is running",
    data: "Dashboard, health, barcode, and export responses",
    steps: "Request page and API routes; inspect response headers",
    expected:
      "CSP, frame, MIME, referrer, opener, and permissions protections are present",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/lib/security/headers.test.ts; e2e/phase-six.spec.ts",
    status: "Passed",
    actual: "Central header contract and browser assertions implemented",
    evidence: "Vitest and Playwright",
    defect: "",
    comments:
      "Production CSP origins must be reconciled when providers are connected",
  },
  {
    id: "TC-SEC-007",
    requirement: "NFR-342; NFR-355",
    module: "Rate Limiting",
    route: "/api/barcodes/[value]; /api/reports/export",
    role: "All authorized",
    priority: "High",
    level: "Unit",
    scenario: "Throttle excessive mock endpoint requests",
    preconditions: "Fixed request window is active",
    data: "Repeated client/scope requests",
    steps: "Send requests through and above the configured limit",
    expected:
      "Allowed calls expose remaining quota; excessive calls return 429 and Retry-After",
    mockScenario: "rate limited",
    automationCandidate: "Yes",
    automationFile: "src/lib/security/rate-limit.test.ts",
    status: "Passed",
    actual:
      "Deterministic window, expiry, remaining, and retry behavior verified",
    evidence: "Vitest",
    defect: "",
    comments:
      "Distributed production limiter remains an infrastructure boundary",
  },
  {
    id: "TC-SEC-008",
    requirement: "NFR-350; NFR-351; NFR-352",
    module: "Observability",
    route: "Server",
    role: "System",
    priority: "High",
    level: "Unit",
    scenario: "Redact sensitive values from structured diagnostics",
    preconditions: "Server logger receives nested context",
    data: "Phone, email, password, correlation ID, and safe count",
    steps: "Write a structured event; inspect serialized output",
    expected:
      "Sensitive identity/credential/payment keys are redacted recursively and safe context remains",
    mockScenario: "error diagnostics",
    automationCandidate: "Yes",
    automationFile: "src/lib/observability/logger.test.ts",
    status: "Passed",
    actual: "Recursive redaction assertions implemented",
    evidence: "Vitest",
    defect: "",
    comments:
      "Central log transport and retention remain production infrastructure",
  },
  {
    id: "TC-OPS-001",
    requirement: "NFR-350; NFR-356",
    module: "Health",
    route: "/api/health",
    role: "System",
    priority: "High",
    level: "Integration",
    scenario: "Report application liveness without dependencies",
    preconditions: "Next.js router is running",
    data: "GET health request",
    steps: "Request liveness endpoint",
    expected: "200, no-store, generic service/status/timestamp response",
    mockScenario: "success",
    automationCandidate: "Yes",
    automationFile: "src/app/api/health/route.test.ts; e2e/phase-six.spec.ts",
    status: "Passed",
    actual: "Route and browser checks implemented",
    evidence: "Vitest and Playwright",
    defect: "",
    comments: "Liveness deliberately does not imply dependency readiness",
  },
  {
    id: "TC-OPS-002",
    requirement: "NFR-328; NFR-350; NFR-356",
    module: "Readiness",
    route: "/api/ready",
    role: "System",
    priority: "High",
    level: "E2E",
    scenario: "Validate configured data source without leaking failures",
    preconditions: "Mock store or API source configured",
    data: "Valid and unavailable data boundaries",
    steps: "Request readiness; repeat with malformed/unavailable source",
    expected:
      "Ready source returns 200; failure returns generic 503 plus correlation ID and preserves data",
    mockScenario: "success and malformed store",
    automationCandidate: "Yes",
    automationFile:
      "e2e/phase-six.spec.ts; src/lib/mock-store/mock-store.test.ts",
    status: "Passed",
    actual:
      "Success path and existing malformed-store preservation are covered",
    evidence: "Playwright and Vitest",
    defect: "",
    comments: "Live API health envelope is API-TODO",
  },
  {
    id: "TC-A11Y-003",
    requirement: "NFR-301; NFR-303; NFR-305",
    module: "Keyboard and Recovery",
    route: "Admin shell and error boundaries",
    role: "All",
    priority: "High",
    level: "E2E",
    scenario: "Skip repeated navigation and focus recovery messages",
    preconditions: "Keyboard-only navigation",
    data: "Dashboard, not-found, and forbidden payroll routes",
    steps: "Tab to skip link; activate; trigger not-found and permission error",
    expected:
      "Focus reaches main content and error heading; recovery controls are named and usable",
    mockScenario: "success, not found, forbidden",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-six.spec.ts",
    status: "Passed",
    actual: "Keyboard skip and focused recovery assertions implemented",
    evidence: "Playwright",
    defect: "",
    comments: "Manual representative screen-reader review remains required",
  },
  {
    id: "TC-A11Y-004",
    requirement: "NFR-302; NFR-306; NFR-307",
    module: "Responsive Accessibility",
    route: "/dashboard",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "Honor reduced motion and minimum touch targets on mobile",
    preconditions: "360px/mobile project and reduced-motion preference",
    data: "Dashboard filter controls",
    steps: "Open dashboard; measure controls; inspect transition duration",
    expected:
      "Interactive controls are at least 44px high and motion is effectively disabled",
    mockScenario: "mobile",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-six.spec.ts",
    status: "Passed",
    actual: "Mobile target and reduced-motion assertions implemented",
    evidence: "Playwright",
    defect: "",
    comments:
      "Manual 200%/400% zoom and forced-colors review remains in release checklist",
  },
  {
    id: "TC-REG-006",
    requirement: "NFR-308; NFR-309; NFR-310; NFR-311",
    module: "Release Quality",
    route: "Repository",
    role: "System",
    priority: "High",
    level: "Regression",
    scenario: "Run portable release gates locally and in CI",
    preconditions: "Node 22 and locked dependencies installed",
    data: "All source, routes, components, tests, and production bundle",
    steps: "Run quality:release and desktop/mobile Playwright",
    expected: "UTF-8, size, format, lint, types, tests, build, and E2E pass",
    mockScenario: "full regression",
    automationCandidate: "Yes",
    automationFile: ".github/workflows/admin-panel-ci.yml",
    status: "Passed",
    actual:
      "Prettier, ESLint, strict TypeScript, 450-file UTF-8, source-size, 65-test Vitest, 51-scenario Playwright, and 53-task production build passed",
    evidence: "Local release verification on 2026-07-31",
    defect: "",
    comments:
      "13 duplicate/device-specific browser cases intentionally skipped; four visual baselines compared cleanly",
  },
  {
    id: "TC-P7-001",
    requirement: "NFR-329; NFR-350; NFR-351",
    module: "Platform Readiness Design",
    route: "/platform",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "Inspect fictional service and provider health",
    preconditions: "Mock owner session",
    data: "Service health and five fictional integration adapters",
    steps:
      "Open platform; inspect service cards, adapter table and safety notice",
    expected:
      "Operational states are readable and every external boundary is explicitly fictional",
    mockScenario: "ready, sandbox, attention and blocked",
    automationCandidate: "Yes",
    automationFile:
      "src/features/platform/tests; e2e/phase-seven-eight.spec.ts",
    status: "Passed",
    actual: "Service, provider and explicit no-live-call boundaries rendered",
    evidence: "Vitest and Playwright desktop/mobile",
    defect: "",
    comments: "No provider call is made",
  },
  {
    id: "TC-P7-002",
    requirement: "NFR-312; NFR-313; NFR-349",
    module: "Migration and Release Design",
    route: "/platform/migrations; /platform/release-readiness",
    role: "Owner",
    priority: "High",
    level: "E2E",
    scenario: "Review mock cutover evidence and go/no-go gates",
    preconditions: "Mock owner session",
    data: "Passed, warning, review and blocked evidence",
    steps:
      "Open migration and release pages; inspect reconciliation and owners",
    expected:
      "Mock evidence is distinguishable from external production blockers",
    mockScenario: "reconciled rehearsal and blocked recovery gate",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-seven-eight.spec.ts",
    status: "Passed",
    actual: "Rehearsal history and release evidence rendered on both devices",
    evidence: "Playwright desktop/mobile",
    defect: "",
    comments: "No production data is migrated",
  },
  {
    id: "TC-P8-001",
    requirement: "FR-165",
    module: "Demand and Reorder Intelligence",
    route: "/insights; /inventory/reorder-suggestions",
    role: "Owner/Manager",
    priority: "Medium",
    level: "E2E",
    scenario: "Review explainable forecasts and reorder suggestions",
    preconditions: "Reports permission and deterministic 26-week mock history",
    data: "Actual/forecast ranges, supplier samples and four suggestions",
    steps: "Open insights; inspect accessible data; open reorder review",
    expected:
      "Confidence, explanations and advisory-only purchase-order boundary are visible",
    mockScenario: "high, medium, low and insufficient data",
    automationCandidate: "Yes",
    automationFile:
      "src/features/optimization/tests; e2e/phase-seven-eight.spec.ts",
    status: "Passed",
    actual:
      "Accessible forecast and advisory reorder/supplier designs rendered",
    evidence: "Vitest and Playwright desktop/mobile",
    defect: "",
    comments: "Recommendations never mutate inventory or procurement",
  },
  {
    id: "TC-P8-002",
    requirement: "FR-123; FR-124; FR-125; NFR-356; NFR-357",
    module: "Customer Growth and Privacy",
    route: "/customers/segments; /loyalty/rewards; /customers/privacy-requests",
    role: "Owner/Manager/Support",
    priority: "High",
    level: "E2E",
    scenario: "Inspect consent, reward liability and privacy-review states",
    preconditions: "Customer view permission",
    data: "Three segments, reward programs and fictional privacy requests",
    steps: "Open each customer-growth route; inspect rules and safety notices",
    expected:
      "Consent eligibility, ledger boundaries and identity/legal-hold states are clear",
    mockScenario: "active, draft, paused, identity check and legal hold",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-seven-eight.spec.ts",
    status: "Passed",
    actual: "Segment, reward and privacy routes rendered with mock boundaries",
    evidence: "Playwright desktop/mobile",
    defect: "",
    comments: "No customer data or loyalty balance is changed",
  },
  {
    id: "TC-P8-003",
    requirement: "FR-119; FR-189; FR-190; FR-191; FR-192; FR-193",
    module: "Finance and Scheduled Reporting",
    route: "/finance/reconciliation; /reports/schedules",
    role: "Owner/Manager",
    priority: "High",
    level: "E2E",
    scenario: "Review exact settlement matches, exceptions and report delivery",
    preconditions: "Reports permission",
    data: "Matched, mismatch, missing reference and delivery states",
    steps: "Open reconciliation; inspect differences; open schedules",
    expected:
      "Only exact matches appear auto-closeable and scheduled artifacts remain fictional",
    mockScenario:
      "matched, amount mismatch, missing internal and failed delivery",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-seven-eight.spec.ts",
    status: "Passed",
    actual: "Exact match, exception and scheduled-delivery states rendered",
    evidence: "Vitest and Playwright desktop/mobile",
    defect: "",
    comments: "No settlement, journal, XLSX, PDF or email is produced",
  },
  {
    id: "TC-P8-004",
    requirement: "FR-167; FR-178; NFR-331",
    module: "Channels and Safe Automation",
    route: "/channels; /automation/rules; /complaints/sla-policies",
    role: "Owner/Manager",
    priority: "High",
    level: "E2E",
    scenario:
      "Inspect review-first channels, allow-listed rules and SLA escalations",
    preconditions: "Order and settings permissions",
    data: "Healthy, attention, paused, approved and review-required states",
    steps: "Open channel, automation and SLA pages",
    expected:
      "No connector or rule can bypass normal order, stock or financial commands",
    mockScenario: "review queues, conflicts, retries and breaches",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-seven-eight.spec.ts",
    status: "Passed",
    actual:
      "Channel, automation and SLA design routes passed responsive checks",
    evidence: "Playwright desktop/mobile",
    defect: "",
    comments: "No external event or background job is dispatched",
  },
  {
    id: "TC-P8-005",
    requirement: "NFR-335; NFR-337; NFR-340",
    module: "Localization and Responsive Design",
    route: "/settings/localization",
    role: "Owner/Manager",
    priority: "Medium",
    level: "E2E",
    scenario: "Review English/Bengali coverage on desktop and mobile",
    preconditions: "Settings view permission",
    data: "Mixed Bangla/Latin text and coverage tables",
    steps: "Open localization route on desktop and 360px/mobile",
    expected:
      "Bangla samples render, tables remain usable and design-only status is explicit",
    mockScenario: "ready, in review and not started",
    automationCandidate: "Yes",
    automationFile:
      "src/features/optimization/tests/components.test.tsx; e2e/phase-seven-eight.spec.ts",
    status: "Passed",
    actual: "Bangla samples and coverage tables rendered on desktop/mobile",
    evidence: "Vitest and Playwright desktop/mobile",
    defect: "",
    comments: "Professional Bengali review remains required",
  },
  {
    id: "TC-P9-001",
    requirement: "NFR-301; NFR-302; NFR-307",
    module: "Mock UAT Control Center",
    route: "/demo",
    role: "Owner/Manager/Cashier/Support",
    priority: "High",
    level: "E2E",
    scenario: "Follow guided cross-module and role-specific walkthroughs",
    preconditions: "Deterministic mock session",
    data: "Six workflows and four role guides",
    steps:
      "Open demo workspace; inspect scenarios and role boundaries; open a starting route",
    expected: "Guidance is responsive, accessible and explicitly fictional",
    mockScenario: "desktop and 360px review",
    automationCandidate: "Yes",
    automationFile: "src/features/demo/tests; e2e/phase-nine.spec.ts",
    status: "Passed",
    actual: "Six workflows and four role guides passed desktop/mobile review",
    evidence: "Vitest and Playwright",
    defect: "",
    comments: "No live provider or production approval is implied",
  },
  {
    id: "TC-P9-002",
    requirement: "NFR-302; NFR-306; NFR-340",
    module: "Staff UAT Checklist",
    route: "/demo",
    role: "All",
    priority: "High",
    level: "Component/E2E",
    scenario: "Track manual review alongside locked automated evidence",
    preconditions: "Demo workspace loaded",
    data: "Five automated and three manual review checks",
    steps:
      "Review progress; select a manual check; verify announcement and percentage",
    expected: "Progress updates accessibly and remains clearly browser-local",
    mockScenario: "63% to 75% progress",
    automationCandidate: "Yes",
    automationFile:
      "src/features/demo/tests/components.test.tsx; e2e/phase-nine.spec.ts",
    status: "Passed",
    actual:
      "Accessible progress interaction passed component and browser tests",
    evidence: "Vitest and Playwright",
    defect: "",
    comments: "Checklist state is not durable sign-off",
  },
  {
    id: "TC-P9-003",
    requirement: "NFR-312; NFR-331; NFR-350",
    module: "Demo Data Safety",
    route: "/demo",
    role: "Owner",
    priority: "High",
    level: "Repository/E2E",
    scenario: "Expose deterministic reset only behind every safety gate",
    preconditions: "Mock data mode; explicit reset flag",
    data: "Canonical version 4 fixtures",
    steps:
      "Verify Owner control; verify Support denial; restore isolated edited fixtures",
    expected:
      "Only Owner can reset and canonical fixtures are restored atomically",
    mockScenario: "enabled Owner and restricted Support",
    automationCandidate: "Yes",
    automationFile:
      "src/features/demo/tests/mock-repository.test.ts; e2e/phase-nine.spec.ts",
    status: "Passed",
    actual:
      "Isolated fixture restoration and role-scoped reset controls passed",
    evidence: "Repository test and Playwright",
    defect: "",
    comments: "Reset never operates in API mode or deletes directories",
  },
  {
    id: "TC-P10-001",
    requirement: "NFR-301; NFR-309; NFR-310",
    module: "Stakeholder Acceptance",
    route: "/demo/acceptance",
    role: "Owner/Manager/Cashier/Support",
    priority: "High",
    level: "Component/E2E",
    scenario:
      "Review the complete route inventory and controlled design freeze",
    preconditions: "Deterministic mock release",
    data: "71 route pages and six freeze records",
    steps:
      "Open acceptance; inspect readiness groups, change policies and evidence owners",
    expected:
      "Counts reconcile and frozen, controlled and external boundaries are explicit",
    mockScenario: "passed and review route groups",
    automationCandidate: "Yes",
    automationFile: "src/features/demo/tests; e2e/phase-ten.spec.ts",
    status: "Passed",
    actual: "All 71 route pages reconciled and six change policies rendered",
    evidence: "Vitest and Playwright",
    defect: "",
    comments: "No production capability is unlocked",
  },
  {
    id: "TC-P10-002",
    requirement: "NFR-302; NFR-306; NFR-340",
    module: "Acceptance and Limitations",
    route: "/demo/acceptance",
    role: "All",
    priority: "High",
    level: "Component/E2E",
    scenario: "Review limitations and rehearse stakeholder selection",
    preconditions: "Acceptance workspace loaded",
    data: "Six limitations and five stakeholder checks",
    steps:
      "Review limitations; select one check; verify progress and local-only notice",
    expected: "Progress updates accessibly without claiming durable approval",
    mockScenario: "0% to 20% local progress",
    automationCandidate: "Yes",
    automationFile:
      "src/features/demo/tests/acceptance-components.test.tsx; e2e/phase-ten.spec.ts",
    status: "Passed",
    actual:
      "Limitations remained visible and local progress changed from 0% to 20%",
    evidence: "Vitest and Playwright",
    defect: "",
    comments: "External governance remains required",
  },
  {
    id: "TC-P10-003",
    requirement: "NFR-301; NFR-302; NFR-307",
    module: "Visual Regression",
    route: "/demo; /demo/acceptance",
    role: "Owner",
    priority: "High",
    level: "Visual E2E",
    scenario: "Compare frozen desktop and mobile mock-release surfaces",
    preconditions: "Windows Playwright baselines committed",
    data: "Four main-content PNG baselines",
    steps: "Render both routes in desktop and mobile projects; compare pixels",
    expected:
      "No unreviewed material visual difference, clipping or compressed mobile freeze table",
    mockScenario: "1280px desktop and 390px mobile",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-ten-visual.spec.ts",
    status: "Passed",
    actual:
      "Four corrected baselines passed manual inspection and clean comparison",
    evidence: "Playwright screenshots and visual review",
    defect: "",
    comments: "Baseline changes require deliberate visual review",
  },
  {
    id: "TC-P11-001",
    requirement: "NFR-301; NFR-309; NFR-310; NFR-350",
    module: "Preview Handoff",
    route: "/demo/release",
    role: "Owner/Manager/Cashier/Support",
    priority: "High",
    level: "Unit/Component/E2E",
    scenario: "Review sanitized version-linked preview evidence",
    preconditions: "Mock data source and Phase 10 frozen baseline",
    data: "Release identity, four gates, 11 routes and four limitations",
    steps:
      "Open release page; review identity, gates, routes, limitations and safe handoff",
    expected:
      "Every role sees fictional-data boundaries without secrets or production claims",
    mockScenario: "development and packaged preview modes",
    automationCandidate: "Yes",
    automationFile: "src/features/preview/tests; e2e/phase-eleven.spec.ts",
    status: "Passed",
    actual:
      "All four roles rendered sanitized identity, gates, routes and limitations",
    evidence: "Vitest and desktop/mobile Playwright",
    defect: "",
    comments: "Hosting remains separately authorized",
  },
  {
    id: "TC-P11-002",
    requirement: "NFR-302; NFR-306; NFR-334; NFR-364",
    module: "Preview Packaging",
    route: "Operator scripts",
    role: "Release operator",
    priority: "High",
    level: "Script/Artifact smoke",
    scenario: "Package and verify the local standalone mock preview",
    preconditions: "Supported Node runtime and clean quality gates",
    data: "Isolated .preview-data and versioned ZIP",
    steps:
      "Initialize; verify; package; compare checksum; extract; run smoke routes",
    expected:
      "Artifact starts locally, seeds canonical fixtures and passes critical routes",
    mockScenario: "local-only deterministic package",
    automationCandidate: "Yes",
    automationFile: "scripts/preview-*.mjs; scripts/zip-directory.mjs",
    status: "Passed",
    actual:
      "Standalone ZIP checksum, extraction, fixture initialization and seven critical routes passed",
    evidence: "preview:package, preview:smoke and preview:verify --artifact",
    defect: "",
    comments: "No backend or public deployment",
  },
  {
    id: "TC-P11-003",
    requirement: "NFR-302; NFR-307; NFR-331",
    module: "Preview Visual Regression",
    route: "/demo/release",
    role: "Owner",
    priority: "High",
    level: "Visual E2E",
    scenario: "Compare the handoff page on desktop and mobile",
    preconditions: "Playwright baselines approved",
    data: "Desktop and 390px mobile release-page images",
    steps: "Render main content in both projects and compare pixels",
    expected: "No unreviewed drift, clipping or unusable responsive layout",
    mockScenario: "desktop and mobile",
    automationCandidate: "Yes",
    automationFile: "e2e/phase-eleven-visual.spec.ts",
    status: "Passed",
    actual:
      "Desktop and mobile release baselines passed comparison and visual inspection",
    evidence: "Playwright screenshots and manual visual review",
    defect: "",
    comments: "Baseline changes require visual inspection",
  },
];
